image: node:16.13.0

pipelines:
  branches:
    master:
      - step:
          name: Testing on client
          caches:
            - node
          script:
            - cd packages/front-end
            - npm install
