image: node:16.13.0

pipelines:
  branches:
    master:
      - step:
          name: Testing on server
          caches:
            - node
          script:
            - cd packages/elt_api
            - npm install
